# ========================================
# CROSSHAIR OVERLAY PRO - CONFIGURATION
# ========================================
# Appuyez sur F5 dans l'application pour recharger

[crosshair]
# Taille du crosshair (en pixels)
size = 25

# Épaisseur des lignes (en pixels)
thickness = 10

# Espace au centre pour le style "classic" (en pixels)
gap = 5

# Couleur du crosshair (format hex)
color = "#00FF00"  # Vert

# Transparence du crosshair (0.0 = invisible, 1.0 = opaque)
alpha = 1.0

# Rotation en degrés (0-360)
rotation = 0

# Style du crosshair: "classic", "dot", "circle", "t", "x", "square", "diamond"
style = "classic"

# Pour style "classic" : utiliser des triangles au lieu de rectangles
triangle_bars = true

# Pour style "circle" : cercle plein ou juste le contour
filled_circle = false

[crosshair.center_dot]
# Activer/désactiver le point central
enabled = true

# Taille du point central (en pixels)
size = 2

# Couleur du point central (format hex)
color = "#FF0000"  # Rouge

# Transparence du point central (0.0-1.0)
alpha = 1.0

[crosshair.outline]
# Activer l'outline (contour noir)
enabled = false

# Épaisseur de l'outline (en pixels)
thickness = 1

# Couleur de l'outline (format hex)
color = "#000000"  # Noir

# Transparence de l'outline (0.0-1.0)
alpha = 0.8

[window]
# Taille de la fenêtre (en pixels)
size = 300

# Opacité globale de la fenêtre (0.0-1.0)
opacity = 1.0

[window.position]
# Centrer automatiquement la fenêtre sur l'écran
center_screen = true

# Position manuelle (ignorée si center_screen = true)
x = 100
y = 100

# Suivre le curseur de la souris
follow_cursor = true

# Décalage par rapport au curseur (en pixels)
offset_x = 0
offset_y = 0

[window.background]
# Activer un fond coloré pour la fenêtre
enabled = false

# Couleur de fond (format hex)
color = "#000000"  # Noir

# Transparence du fond (0.0-1.0)
alpha = 0.1

[effects]
# ========================================
# EFFETS VISUELS
# ========================================


[effects.pulse]
# Effet de pulsation/clignotement
enabled = false

# Vitesse du pulse (en Hz, cycles par seconde)
speed = 2.0

# Transparence minimum (0.0-1.0)
min_alpha = 0.3

# Transparence maximum (0.0-1.0)
max_alpha = 1.0

[effects.shake]
# Effet de tremblement
enabled = false

# Intensité du tremblement (en pixels)
intensity = 1.0

# Vitesse du tremblement (en Hz)
speed = 1.0

[effects.rainbow]
# Effet arc-en-ciel
enabled = true

# Vitesse de rotation des couleurs (en Hz)
speed = 1.0

# Saturation des couleurs (0.0-1.0)
saturation = 1.0

# Luminosité des couleurs (0.0-1.0)
brightness = 1.0

# ========================================
# EFFETS DE SOURIS - NOUVEAUTÉ !
# ========================================

[effects.mouse]
# Activer/désactiver les effets de souris
enabled = true

# Effet de Gap - Écarte ou rapproche le crosshair au clic
[effects.mouse.gap_effect]
enabled = true
mode = "expand"        # "expand", "contract", "toggle"
intensity = 5        # Multiplicateur de l'effet (0.0-5.0)
smooth_transition = true

# Configuration par bouton pour l'effet de gap
[effects.mouse.gap_effect.button_binding]
left_click = "expand"    # Clic gauche écarte le crosshair
right_click = "contract" # Clic droit rapproche le crosshair
# middle_click = null    # Molette pas d'effet (optionnel)

# Effet de Visibilité - Cache des parties du crosshair au clic
[effects.mouse.visibility_effect]
enabled = false
hide_mode = "center"      # "full", "left", "right", "top", "bottom", "center", "sides", "vertical", "cross"
fade_percentage = 0.2     # Pourcentage de disparition (0.0-1.0)
smooth_fade = true
fade_speed = 5.0          # Vitesse de disparition (0.1-10.0, plus élevé = plus rapide)

# Configuration par bouton pour l'effet de visibilité
[effects.mouse.visibility_effect.button_binding]
left_click = "top"    # Clic gauche cache le centre
right_click = "sides"    # Clic droit cache les côtés
middle_click = "full"    # Molette cache tout

# ========================================
# PRESETS RECOMMANDÉS
# ========================================

# GAMING DISCRET:
# style = "classic", size = 15, thickness = 1, gap = 3
# alpha = 0.8, outline.enabled = true

# TRIANGLES STYLE:
# style = "classic", triangle_bars = true, thickness = 8
# gap = 3, outline.enabled = true

# CERCLE PLEIN:
# style = "circle", filled_circle = true, size = 20
# gap = 5, color = "#FF00FF"

# EFFET NÉON:
# style = "circle", color = "#00FFFF", rainbow.enabled = true
# rainbow.speed = 0.5

# RAINBOW PULSE:
# style = "circle", rainbow.enabled = true, pulse.enabled = true
# rainbow.speed = 0.5, pulse.speed = 1.5

# SNIPER DOT:
# style = "dot", size = 3, color = "#FF0000"
# center_dot.enabled = false

# CARRÉ ROTATIF:
# style = "square", rotation = 45.0, thickness = 3
# outline.enabled = true

# LOSANGE ELEGANTE:
# style = "diamond", color = "#FF00FF", gap = 8
# outline.enabled = true

# SHAKE EFFECT:
# style = "x", shake.enabled = true, shake.intensity = 2.0
# shake.speed = 15.0

# MOUSE EFFECTS - SNIPER MODE:
# effects.mouse.gap_effect.enabled = true, mode = "expand"
# effects.mouse.gap_effect.intensity = 3.0, smooth_transition = false

# MOUSE EFFECTS - PRECISION MODE:
# effects.mouse.gap_effect.enabled = true, mode = "contract"
# effects.mouse.gap_effect.intensity = 1.5

# MOUSE EFFECTS - CLARITY MODE:
# effects.mouse.visibility_effect.enabled = true, hide_mode = "center"
# effects.mouse.visibility_effect.fade_percentage = 1.0, fade_speed = 8.0

# MOUSE EFFECTS - VITESSE LENTE:
# effects.mouse.visibility_effect.fade_speed = 1.0 (très lent)

# MOUSE EFFECTS - VITESSE RAPIDE:
# effects.mouse.visibility_effect.fade_speed = 10.0 (instantané)

# ============================================
# EXEMPLES DE CONFIGURATIONS
# ============================================

# Crosshair classique vert avec point rouge:
# style = "classic", color = "#00FF00", center_dot.color = "#FF0000"

# Point simple rouge:
# style = "dot", center_dot.enabled = true, center_dot.color = "#FF0000"

# Croix complète bleue:
# style = "cross", color = "#0066FF", gap = 0

# Cercle cyan:
# style = "circle", color = "#00FFFF", size = 30

# Crosshair gaming (petit et précis):
# size = 15, thickness = 1, gap = 3, style = "classic"

# Crosshair large et visible:
# size = 40, thickness = 3, gap = 8, style = "cross" 